.class public final Lorg/xbet/client1/presentation/activity/AppScreens;
.super Ljava/lang/Object;
.source "AppScreens.kt"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lorg/xbet/client1/presentation/activity/AppScreens$UserInfoFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ShowcaseFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$MessagesFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$BetHistoryFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ShareCouponScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$BetInfoFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$AlternativeInfoFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$BatTransactionsHistoryFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SaleCouponFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$InsuranceFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$EditCouponFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$OneXGamesFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CasinoFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$AggregatorMainScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$AggregatorRecommendationScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CouponVPFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$GenerateCouponFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$FavoriteFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$FinBetFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$MySubscriptionsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$DayExpressFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CouponScannerFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$InfoFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$OfficeSupportFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$MailingManagementFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$NightModeFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$OneClickSettingsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$MakeBetSettingsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$PushNotifySettingsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$PinCodeSettingsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$PersonalDataFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SocialNetworksFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$TestSectionFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$OnoboardingFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$NewsMainFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$BetConstructorFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$TransactionsHistoryFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$AnnualReportFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$PromoListFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$WalletsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$AddWalletFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$BonusesFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$BonusesPromotionFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$BonusAgreementsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$PromoCheckFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$PromoShopScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$PromoCategoryScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$PromoShopDetailScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SettingsCoefTypeFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ProfileEditFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SupportCallbackFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$TwoFactorFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$AddTwoFactorFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$RemoveTwoFactorFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$AddPinCodeFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$RemovePinCodeFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ChangePinCodeFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SecurityFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SecretQuestionFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$AuthHistoryFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ChangePasswordFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ChangeEmailFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$EmailConfirmBindFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$EmailSendCodeFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$RestorePasswordFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$BindingPhoneFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ActivationBySmsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$RegistrationActivationFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ActivationByEmailFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ActivationEmailFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ActivationRestoreFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$PinLoginFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SetNewPasswordFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$EmptyAccountsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$AdditionalInformationFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ChangePhoneFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$IdentificationFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SumSubIdentificationFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CupisFillWithDocsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CupisFillWithDocsAstrabetFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CupisFillWithDocsMelbetRuFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CupisCheckPhotoFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$EditProfileWithDocsFragmentMelbetGhScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$QuestionFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$TvBetJackpotFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$LoginFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ConfirmNewPlaceScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ConfirmQRScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$RegistrationFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$RegistrationWrapperFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$RegistrationUltraFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CouponEditGameEventFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$NewsCatalogFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$NewsCatalogTypeFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CoreLineLiveFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$FeedsLineLiveFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ChampGamesFeedFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$BetOnYoursLineLiveFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ResultsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ResultsHistorySearchFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$RulesFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$TotoHolderFragmentScreenType;,
        Lorg/xbet/client1/presentation/activity/AppScreens$TotoHistoryFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$TotoAccurateOutcomesScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SearchEventsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SportGameFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SportGameStartFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SportGameTwoTeamScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SportGameTwentyOneScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SportGameDurakScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SportGameDiceScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SportGamePokerScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SportGameSekaScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SportSeaBattleScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SportVictoryFormulaScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SportGameOneTeamScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$FavoriteSportGameScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$DotaStatisticFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SimpleGameStatisticFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$NotificationSportGameScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$PlayerInfoScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$PopularSettings;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ShakeSettings;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ShareAppByQrScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$PopularEventsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ResultsEventsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ResultsLiveEventsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SuppLibFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SupportFaqAnswerFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SuppLibChatFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$VipClubFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$VipCashBackFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$OneMoreCashbackScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$NewsPagerFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$NewsPagerNewFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$PredictionsScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CountryChooserScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CupisIdentificationFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CupisFillFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$EditLimitFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SetLimitFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$FinancialTestFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$FinancialSecurityScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$AuthenticatorOnboardingScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$AuthenticatorScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$SportsFilterScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ChooseRegionScreenKZ;,
        Lorg/xbet/client1/presentation/activity/AppScreens$Payment;,
        Lorg/xbet/client1/presentation/activity/AppScreens$Reward;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ConfirmRestoreFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$AppAndWinFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CaseGoMainFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CaseGoInventoryFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CaseGoTicketsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$UserTicketsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$AppAndWinTicketsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$AppAndWinResultsFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CoefTrackFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$MainMenuFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ConfirmRestoreWithAuthFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$NewsWinnerFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$F1Statistic;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CSStatistic;,
        Lorg/xbet/client1/presentation/activity/AppScreens$ChromeTabsLoading;,
        Lorg/xbet/client1/presentation/activity/AppScreens$WebGame;,
        Lorg/xbet/client1/presentation/activity/AppScreens$OneXGamesCashbackFragmentScreen;,
        Lorg/xbet/client1/presentation/activity/AppScreens$CashbackChoosingFragmentScreen;
    }
.end annotation

.annotation runtime Lkotlin/Metadata;
    d1 = {
        "\u0000\r\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0003\u0008\u00a9\u0001\u0008\u00c6\u0002\u0018\u00002\u00020\u0001:\u00d1\u0001\u0003\u0004\u0005\u0006\u0007\u0008\t\n\u000b\u000c\r\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a\u001b\u001c\u001d\u001e\u001f !\"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\u007f\u0080\u0001\u0081\u0001\u0082\u0001\u0083\u0001\u0084\u0001\u0085\u0001\u0086\u0001\u0087\u0001\u0088\u0001\u0089\u0001\u008a\u0001\u008b\u0001\u008c\u0001\u008d\u0001\u008e\u0001\u008f\u0001\u0090\u0001\u0091\u0001\u0092\u0001\u0093\u0001\u0094\u0001\u0095\u0001\u0096\u0001\u0097\u0001\u0098\u0001\u0099\u0001\u009a\u0001\u009b\u0001\u009c\u0001\u009d\u0001\u009e\u0001\u009f\u0001\u00a0\u0001\u00a1\u0001\u00a2\u0001\u00a3\u0001\u00a4\u0001\u00a5\u0001\u00a6\u0001\u00a7\u0001\u00a8\u0001\u00a9\u0001B\u0007\u0008\u0002\u00a2\u0006\u0002\u0010\u0002\u00a8\u0006\u00aa\u0001"
    }
    d2 = {
        "Lorg/xbet/client1/presentation/activity/AppScreens;",
        "",
        "()V",
        "ActivationByEmailFragmentScreen",
        "ActivationBySmsFragmentScreen",
        "ActivationEmailFragmentScreen",
        "ActivationRestoreFragmentScreen",
        "AddPinCodeFragmentScreen",
        "AddTwoFactorFragmentScreen",
        "AddWalletFragmentScreen",
        "AdditionalInformationFragmentScreen",
        "AggregatorMainScreen",
        "AggregatorRecommendationScreen",
        "AlternativeInfoFragmentScreen",
        "AnnualReportFragmentScreen",
        "AppAndWinFragmentScreen",
        "AppAndWinResultsFragmentScreen",
        "AppAndWinTicketsFragmentScreen",
        "AuthHistoryFragmentScreen",
        "AuthenticatorOnboardingScreen",
        "AuthenticatorScreen",
        "BatTransactionsHistoryFragmentScreen",
        "BetConstructorFragmentScreen",
        "BetHistoryFragmentScreen",
        "BetInfoFragmentScreen",
        "BetOnYoursLineLiveFragmentScreen",
        "BindingPhoneFragmentScreen",
        "BonusAgreementsFragmentScreen",
        "BonusesFragmentScreen",
        "BonusesPromotionFragmentScreen",
        "CSStatistic",
        "CaseGoInventoryFragmentScreen",
        "CaseGoMainFragmentScreen",
        "CaseGoTicketsFragmentScreen",
        "CashbackChoosingFragmentScreen",
        "CasinoFragmentScreen",
        "ChampGamesFeedFragmentScreen",
        "ChangeEmailFragmentScreen",
        "ChangePasswordFragmentScreen",
        "ChangePhoneFragmentScreen",
        "ChangePinCodeFragmentScreen",
        "ChooseRegionScreenKZ",
        "ChromeTabsLoading",
        "CoefTrackFragmentScreen",
        "ConfirmNewPlaceScreen",
        "ConfirmQRScreen",
        "ConfirmRestoreFragmentScreen",
        "ConfirmRestoreWithAuthFragmentScreen",
        "CoreLineLiveFragmentScreen",
        "CountryChooserScreen",
        "CouponEditGameEventFragmentScreen",
        "CouponScannerFragmentScreen",
        "CouponVPFragmentScreen",
        "CupisCheckPhotoFragmentScreen",
        "CupisFillFragmentScreen",
        "CupisFillWithDocsAstrabetFragmentScreen",
        "CupisFillWithDocsFragmentScreen",
        "CupisFillWithDocsMelbetRuFragmentScreen",
        "CupisIdentificationFragmentScreen",
        "DayExpressFragmentScreen",
        "DotaStatisticFragmentScreen",
        "EditCouponFragmentScreen",
        "EditLimitFragmentScreen",
        "EditProfileWithDocsFragmentMelbetGhScreen",
        "EmailConfirmBindFragmentScreen",
        "EmailSendCodeFragmentScreen",
        "EmptyAccountsFragmentScreen",
        "F1Statistic",
        "FavoriteFragmentScreen",
        "FavoriteSportGameScreen",
        "FeedsLineLiveFragmentScreen",
        "FinBetFragmentScreen",
        "FinancialSecurityScreen",
        "FinancialTestFragmentScreen",
        "GenerateCouponFragmentScreen",
        "IdentificationFragmentScreen",
        "InfoFragmentScreen",
        "InsuranceFragmentScreen",
        "LoginFragmentScreen",
        "MailingManagementFragmentScreen",
        "MainMenuFragmentScreen",
        "MakeBetSettingsFragmentScreen",
        "MessagesFragmentScreen",
        "MySubscriptionsFragmentScreen",
        "NewsCatalogFragmentScreen",
        "NewsCatalogTypeFragmentScreen",
        "NewsMainFragmentScreen",
        "NewsPagerFragmentScreen",
        "NewsPagerNewFragmentScreen",
        "NewsWinnerFragmentScreen",
        "NightModeFragmentScreen",
        "NotificationSportGameScreen",
        "OfficeSupportFragmentScreen",
        "OneClickSettingsFragmentScreen",
        "OneMoreCashbackScreen",
        "OneXGamesCashbackFragmentScreen",
        "OneXGamesFragmentScreen",
        "OnoboardingFragmentScreen",
        "Payment",
        "PersonalDataFragmentScreen",
        "PinCodeSettingsFragmentScreen",
        "PinLoginFragmentScreen",
        "PlayerInfoScreen",
        "PopularEventsFragmentScreen",
        "PopularSettings",
        "PredictionsScreen",
        "ProfileEditFragmentScreen",
        "PromoCategoryScreen",
        "PromoCheckFragmentScreen",
        "PromoListFragmentScreen",
        "PromoShopDetailScreen",
        "PromoShopScreen",
        "PushNotifySettingsFragmentScreen",
        "QuestionFragmentScreen",
        "RegistrationActivationFragmentScreen",
        "RegistrationFragmentScreen",
        "RegistrationUltraFragmentScreen",
        "RegistrationWrapperFragmentScreen",
        "RemovePinCodeFragmentScreen",
        "RemoveTwoFactorFragmentScreen",
        "RestorePasswordFragmentScreen",
        "ResultsEventsFragmentScreen",
        "ResultsFragmentScreen",
        "ResultsHistorySearchFragmentScreen",
        "ResultsLiveEventsFragmentScreen",
        "Reward",
        "RulesFragmentScreen",
        "SaleCouponFragmentScreen",
        "SearchEventsFragmentScreen",
        "SecretQuestionFragmentScreen",
        "SecurityFragmentScreen",
        "SetLimitFragmentScreen",
        "SetNewPasswordFragmentScreen",
        "SettingsCoefTypeFragmentScreen",
        "ShakeSettings",
        "ShareAppByQrScreen",
        "ShareCouponScreen",
        "ShowcaseFragmentScreen",
        "SimpleGameStatisticFragmentScreen",
        "SocialNetworksFragmentScreen",
        "SportGameDiceScreen",
        "SportGameDurakScreen",
        "SportGameFragmentScreen",
        "SportGameOneTeamScreen",
        "SportGamePokerScreen",
        "SportGameSekaScreen",
        "SportGameStartFragmentScreen",
        "SportGameTwentyOneScreen",
        "SportGameTwoTeamScreen",
        "SportSeaBattleScreen",
        "SportVictoryFormulaScreen",
        "SportsFilterScreen",
        "SumSubIdentificationFragmentScreen",
        "SuppLibChatFragmentScreen",
        "SuppLibFragmentScreen",
        "SupportCallbackFragmentScreen",
        "SupportFaqAnswerFragmentScreen",
        "TestSectionFragmentScreen",
        "TotoAccurateOutcomesScreen",
        "TotoHistoryFragmentScreen",
        "TotoHolderFragmentScreenType",
        "TransactionsHistoryFragmentScreen",
        "TvBetJackpotFragmentScreen",
        "TwoFactorFragmentScreen",
        "UserInfoFragmentScreen",
        "UserTicketsFragmentScreen",
        "VipCashBackFragmentScreen",
        "VipClubFragmentScreen",
        "WalletsFragmentScreen",
        "WebGame",
        "app_prodRelease"
    }
    k = 0x1
    mv = {
        0x1,
        0x7,
        0x1
    }
    xi = 0x30
.end annotation


# static fields
.field public static final INSTANCE:Lorg/xbet/client1/presentation/activity/AppScreens;
    .annotation build Lorg/jetbrains/annotations/NotNull;
    .end annotation
.end field


# direct methods
.method static constructor <clinit>()V
    .locals 1

    new-instance v0, Lorg/xbet/client1/presentation/activity/AppScreens;

    invoke-direct {v0}, Lorg/xbet/client1/presentation/activity/AppScreens;-><init>()V

    sput-object v0, Lorg/xbet/client1/presentation/activity/AppScreens;->INSTANCE:Lorg/xbet/client1/presentation/activity/AppScreens;

    return-void
.end method

.method private constructor <init>()V
    .locals 0

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
